// <auto-generated />
using LoginAndBoard.UserControl;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace LoginAndBoard.Migrations.UserAccountMigrations
{
    [DbContext(typeof(UserAccount))]
    [Migration("20190116211820_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.1-servicing-10028");

            modelBuilder.Entity("LoginAndBoard.UserControl.Blog", b =>
                {
                    b.Property<int>("BlogId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Url");

                    b.HasKey("BlogId");

                    b.ToTable("Blog");
                });

            modelBuilder.Entity("LoginAndBoard.UserControl.Join", b =>
                {
                    b.Property<string>("UserID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("UserEmail")
                        .IsRequired();

                    b.Property<string>("UserName")
                        .IsRequired();

                    b.Property<string>("UserPW")
                        .IsRequired();

                    b.HasKey("UserID");

                    b.ToTable("JoinUser");
                });

            modelBuilder.Entity("LoginAndBoard.UserControl.Login", b =>
                {
                    b.Property<string>("UserID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("UserPW")
                        .IsRequired();

                    b.HasKey("UserID");

                    b.ToTable("LoginUser");
                });

            modelBuilder.Entity("LoginAndBoard.UserControl.Post", b =>
                {
                    b.Property<int>("PostId")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("BlogId");

                    b.Property<string>("Content");

                    b.Property<string>("LoginUserID");

                    b.Property<string>("Title");

                    b.HasKey("PostId");

                    b.HasIndex("BlogId");

                    b.HasIndex("LoginUserID");

                    b.ToTable("Post");
                });

            modelBuilder.Entity("LoginAndBoard.UserControl.Post", b =>
                {
                    b.HasOne("LoginAndBoard.UserControl.Blog", "Blog")
                        .WithMany("Posts")
                        .HasForeignKey("BlogId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("LoginAndBoard.UserControl.Login")
                        .WithMany("Users")
                        .HasForeignKey("LoginUserID");
                });
#pragma warning restore 612, 618
        }
    }
}
